# Generated by Django 5.1.1 on 2024-10-13 18:47

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_remove_clock_clock_unique_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="break_time",
            field=models.IntegerField(default=1, verbose_name="breaktime"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.CharField(
                choices=[("clock_in", "In"), ("clock_out", "Out")],
                default="In",
                max_length=20,
                verbose_name="in/out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="location",
            field=models.CharField(
                choices=[("office", "Office"), ("telework", "Telework")],
                default="Office",
                max_length=20,
                verbose_name="location",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.DateTimeField(
                default="2024-10-14 03:47:48", verbose_name="datetime"
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                default=attendance.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=100, verbose_name="department"),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.department",
                verbose_name="department",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(
                default=attendance.models.create_id,
                editable=False,
                max_length=6,
                primary_key=True,
                serialize=False,
                verbose_name="user id",
            ),
        ),
    ]
