# Generated by Django 5.1.1 on 2024-10-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_clock_break_time_alter_clock_clock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.DateTimeField(
                default="2024-10-15 23:48:36", verbose_name="datetime"
            ),
        ),
    ]
