# Generated by Django 5.1.1 on 2024-10-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_clock_time_stamp"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clock",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="clock",
            name="date_stamp",
            field=models.DateField(default="2024-10-19", verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(default="03:49:10", verbose_name="time"),
        ),
        migrations.AlterUniqueTogether(
            name="clock",
            unique_together={("user", "date_stamp", "clock")},
        ),
    ]
