# Generated by Django 5.1.1 on 2024-10-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_clock_unique_together_clock_date_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(default="04:28:20", verbose_name="time"),
        ),
    ]
