# Generated by Django 5.1.1 on 2024-10-18 20:58

import attendance.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0007_alter_clock_time_stamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.CharField(
                choices=[("IN", "In"), ("OUT", "Out")],
                default="In",
                max_length=20,
                verbose_name="in/out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(default="05:58:02", verbose_name="time"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                default=attendance.models.User,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="attendance.department",
                verbose_name="department",
            ),
        ),
    ]
