# Generated by Django 5.1.1 on 2024-10-20 16:08

import attendance.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_alter_clock_clock_alter_clock_time_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="break_time",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                max_digits=4,
                verbose_name="breaktime",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="date_stamp",
            field=models.DateField(
                default=attendance.models.Clock.Now.date, verbose_name="date"
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(
                default=attendance.models.Clock.Now.time, verbose_name="time"
            ),
        ),
    ]
