# Generated by Django 5.1.1 on 2024-11-06 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_clock_break_time_alter_clock_date_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="date_stamp",
            field=models.DateField(verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(verbose_name="time"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
    ]
