# Generated by Django 5.1.1 on 2024-11-18 15:04

import util.now
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_clock_date_stamp_alter_clock_time_stamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="date_stamp",
            field=models.DateField(default=util.now.Now.date_str, verbose_name="date"),
        ),
        migrations.AlterField(
            model_name="clock",
            name="time_stamp",
            field=models.TimeField(default=util.now.Now.time_str, verbose_name="time"),
        ),
    ]
