# Generated by Django 5.1.1 on 2024-12-15 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_codemaster_clockcorrect_fare_paidleave_payperiod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "clock"},
                on_delete=django.db.models.deletion.PROTECT,
                to="attendance.codemaster",
                verbose_name="in/out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clock",
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="attendance.department",
                verbose_name="department",
            ),
        ),
    ]
