# Generated by Django 5.1.1 on 2024-12-15 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_clock_clock_alter_clock_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "clock"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clock_codes",
                to="attendance.codemaster",
                verbose_name="in/out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="location",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "location"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_codes",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clocks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="clockcorrect",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clockcorrect",
            name="status",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="clockcorrect",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_workflows_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fare",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fare",
            name="status",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="fare",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_workflows_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="status",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_workflows_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="approver",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="status",
            field=models.ForeignKey(
                default="0",
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_workflows_requested",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="attendance.department",
                verbose_name="department",
            ),
        ),
    ]
