# Generated by Django 5.1.15 on 2026-08-27 04:14

import django.db.models.deletion
import util.now
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0014_alter_clock_clock_alter_clock_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clockcorrect",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="clockcorrect",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="fare",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="fare",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="end_date",
            field=models.DateField(default=util.now.Now.date_str),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="start_date",
            field=models.DateField(default=util.now.Now.date_str),
        ),
        migrations.AlterField(
            model_name="paidleave",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="approver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_workflows_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="payperiod",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "workflow_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_workflows_status",
                to="attendance.codemaster",
            ),
        ),
    ]
