# Generated by Django 5.1.15 on 2026-08-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0016_seed_code_master"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clock",
            name="clock",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "clock"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clock_codes",
                to="attendance.codemaster",
                verbose_name="in/out",
            ),
        ),
        migrations.AlterField(
            model_name="clock",
            name="location",
            field=models.ForeignKey(
                limit_choices_to={"code_type": "location"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="location_codes",
                to="attendance.codemaster",
            ),
        ),
    ]
